project:
  type: website

website:
  title: "Margot Berton"
  site-url: https://margotbtn.github.io # To comment to test locally
  site-path: /portfolio/ # To comment to test locally
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Projects
        menu:
          - href: projects/project1.qmd
            text: Project 1
          - href: projects/project2.qmd
            text: Project 2
          - href: projects/project3.qmd
            text: Project 3
    right:
      - text: '<img src="images/icons/github-svgrepo-com.svg" width="24">'
        href: https://github.com/margotbtn/
      - text: '<img src="images/icons/linkedin-svgrepo-com.svg" width="24">'
        href: https://www.linkedin.com/in/margot-berton/
  search: false

format:
  html:
    theme: cosmo
    css: styles.css