project:
  type: website

website:
  title: "Margot Berton | Data Scientist"
  site-url: https://margotbtn.github.io
  site-path: /portfolio/
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Projects
        menu:
          - href: projects/project1.qmd
            text: Project 1
          - href: projects/project2.qmd
            text: Project 2
          - href: projects/project3.qmd
            text: Project 3

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true