name: Render Quarto site

on:
  push:
    branches:
      - main  # branche qui d√©clenche le build

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Install R
    - name: Setup R
      uses: r-lib/actions/setup-r@v2

    # Install Quarto
    - name: Install Quarto
      run: |
        wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.9.16/quarto-1.9.16-linux-amd64.deb
        sudo gdebi -n quarto-1.9.16-linux-amd64.deb

    # Render the site
    - name: Render Quarto site
      run: quarto render

    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
